# Generated by Django 5.0 on 2023-12-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_game_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='chips',
            field=models.IntegerField(default=5000),
        ),
    ]
