# Generated by Django 5.0 on 2023-12-24 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_game_app', '0002_player_point_alter_player_chips'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='deck',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='game',
            name='num_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='river_cards',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poker_game_app.game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.IntegerField(default=4),
        ),
    ]
