# Generated by Django 5.0 on 2024-01-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_game_app', '0006_remove_game_river_cards_game_river_card1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='deck',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
