# Generated by Django 5.0 on 2024-01-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_game_app', '0007_alter_game_deck_alter_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
