# Generated by Django 5.0 on 2024-01-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_game_app', '0008_alter_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hand',
            field=models.CharField(default='', max_length=50),
        ),
    ]
