# Generated by Django 5.0 on 2024-01-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_game_app', '0009_player_hand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='hand',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
